language: python
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
install:
  - pip install six coveralls deluge-client requests
script:
  - nosetests --with-coverage --cover-package=autotorrent
after_success:
  - coveralls